#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Thu Aug  7 11:46:00 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.label_1 = wx.StaticText(self.panel_3, wx.ID_ANY, _("Cozy client configuration"), style=wx.ALIGN_CENTRE)
        self.static_line_1 = wx.StaticLine(self.panel_3, wx.ID_ANY)
        self.label_6 = wx.StaticText(self.panel_3, wx.ID_ANY, _("Fill bellow fields with your Cozy informations to start the file synchronization."))
        self.static_line_3 = wx.StaticLine(self.panel_3, wx.ID_ANY)
        self.label_2 = wx.StaticText(self.panel_3, wx.ID_ANY, _("URL of your Cozy"))
        self.text_ctrl_1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, _("https://mycozy.cozycloud.cc"), style=wx.TE_AUTO_URL)
        self.label_3 = wx.StaticText(self.panel_3, wx.ID_ANY, _("Password of your Cozy"))
        self.text_ctrl_2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.label_5 = wx.StaticText(self.panel_3, wx.ID_ANY, _("Device name"))
        self.text_ctrl_4 = wx.TextCtrl(self.panel_3, wx.ID_ANY, _("myhost-1234"))
        self.label_4 = wx.StaticText(self.panel_3, wx.ID_ANY, _("Syncronized folder"))
        self.text_ctrl_3 = wx.TextCtrl(self.panel_3, wx.ID_ANY, _("/home/kload/yolo"))
        self.button_2 = wx.Button(self.panel_3, wx.ID_ANY, _("Select folder"))
        self.static_line_2 = wx.StaticLine(self.panel_3, wx.ID_ANY)
        self.button_1 = wx.Button(self.panel_3, wx.ID_ANY, _("Discard changes"))
        self.button_1_copy = wx.Button(self.panel_3, wx.ID_ANY, _("Save changes"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        self.SetSize((400, 500))
        self.label_1.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_2.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_3.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_5.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_4.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add((30, 20), 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_6, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_2, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_4.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_3, 0, wx.EXPAND, 0)
        sizer_4.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_5, 0, wx.EXPAND, 0)
        sizer_4.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_4, 0, wx.EXPAND, 0)
        sizer_4.Add(self.text_ctrl_3, 0, wx.EXPAND, 0)
        sizer_4.Add(self.button_2, 0, wx.ALIGN_RIGHT, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_1_copy, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_4)
        sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_2.Add((30, 20), 0, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()