#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Jul 29 14:12:39 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class CozyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CozyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_title = wx.StaticText(self, wx.ID_ANY, _("\nSynchronized devices\n"), style=wx.ALIGN_CENTRE)
        self.device_list = wx.ListBox(self, wx.ID_ANY, choices=[_("device1"), _("device2"), _("device3")], style=wx.LB_SINGLE | wx.LB_EXTENDED | wx.LB_ALWAYS_SB | wx.LB_SORT)
        self.add_device_button = wx.Button(self, wx.ID_ANY, _("Add device"))
        self.edit_device_button = wx.Button(self, wx.ID_ANY, _("Edit device"))
        self.remove_device_button = wx.Button(self, wx.ID_ANY, _("Remove device"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX_DCLICK, self.change_selected_device, self.device_list)
        self.Bind(wx.EVT_BUTTON, self.add_new_device, self.add_device_button)
        self.Bind(wx.EVT_BUTTON, self.edit_device, self.edit_device_button)
        self.Bind(wx.EVT_BUTTON, self.remove_device, self.remove_device_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CozyFrame.__set_properties
        self.SetTitle(_("Cozy FUSE client configuration"))
        self.SetSize((400, 400))
        self.SetFocus()
        self.window_title.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.device_list.SetMinSize((300, 300))
        self.device_list.SetFocus()
        self.device_list.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CozyFrame.__do_layout
        cozy_sizer = wx.BoxSizer(wx.VERTICAL)
        button_grid = wx.GridSizer(1, 3, 0, 0)
        cozy_sizer.Add(self.window_title, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        cozy_sizer.Add(self.device_list, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        button_grid.Add(self.add_device_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        button_grid.Add(self.edit_device_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        button_grid.Add(self.remove_device_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        cozy_sizer.Add(button_grid, 1, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(cozy_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

    def change_selected_device(self, event):  # wxGlade: CozyFrame.<event_handler>
        print "Event handler 'change_selected_device' not implemented!"
        event.Skip()

    def add_new_device(self, event):  # wxGlade: CozyFrame.<event_handler>
        print "Event handler 'add_new_device' not implemented!"
        event.Skip()

    def edit_device(self, event):  # wxGlade: CozyFrame.<event_handler>
        print "Event handler 'edit_device' not implemented!"
        event.Skip()

    def remove_device(self, event):  # wxGlade: CozyFrame.<event_handler>
        print "Event handler 'remove_device' not implemented!"
        event.Skip()

# end of class CozyFrame
class CozyFuse(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        cozy_frame = CozyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(cozy_frame)
        cozy_frame.Show()
        return 1

# end of class CozyFuse

if __name__ == "__main__":
    gettext.install("cozyfuse") # replace with the appropriate catalog name

    cozyfuse = CozyFuse(0)
    cozyfuse.MainLoop()
